### ISSUE TITLE
Unwanted blank space in RDF namespace creation

### ISSUE THREAD

**Issue by floverde** [rdfjs-base/serializer-turtle#14]
The RDF namespace (file: `lib/namespaces.js`, line: `3`, [link](https://github.com/rdfjs-base/serializer-turtle/blob/1447d79524af0fad52ab0e7c16deda644689e35f/lib/namespaces.js#L3)) is created by prepending a whitespace before the URL:

```jsx
// Current
const rdf = namespace(' http://www.w3.org/1999/02/22-rdf-syntax-ns#')
```

Could you please remove that whitespace, as shown below?

```jsx
// Wanted
const rdf = namespace('http://www.w3.org/1999/02/22-rdf-syntax-ns#')
```

Thanks

**Comment by bergos** [comment]
@floverde Thanks a lot for reporting and the PR!

Version changes in the `package.json` should be part of a separate version increase commit done by the `npm version` command. To avoid round trips, I created a separate PR with the same change and also some tests for the util functions. The fix is included in the v1.1.4 release.
